# Generated by Django 5.0.2 on 2024-04-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_card',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
