# Generated by Django 5.0.2 on 2024-04-15 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_add_card_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_card',
            name='total',
            field=models.IntegerField(default=1),
        ),
    ]
